"""Email a generated report over SMTP, only to allow-listed recipients.

The allow-list is the abuse control: this app is public, so an open "send to any address" button would be a
spam relay. Subject and body come from a fixed template around the report, never from the recipient field.
"""
import logging
import re
import smtplib
import ssl
import unicodedata
from email.message import EmailMessage

from app.analytics import Report
from app.config import get_settings

log = logging.getLogger("fireline.email")

ADDRESS = re.compile(r"^[^@\s,;<>\"()\[\]\\]+@[^@\s,;<>\"()\[\]\\]+\.[^@\s,;<>\"()\[\]\\]+$")
TIMEOUT_S = 20


class EmailError(Exception):
    """Safe to show to the user."""


def parse_allowlist(raw: str) -> list[str]:
    return [e.strip().lower() for e in raw.split(",") if e.strip()]


def is_allowed(address: str, allowlist: list[str]) -> bool:
    """Entries: an exact address ("ops@acme.com") or a domain ("@acme.com" or "acme.com"). No wildcards."""
    address = address.strip().lower()
    if not ADDRESS.match(address):
        return False
    domain = address.rsplit("@", 1)[1]
    for entry in allowlist:
        if "@" in entry.lstrip("@"):
            if address == entry:
                return True
        elif domain == entry.lstrip("@"):
            return True
    return False


def email_configured() -> bool:
    s = get_settings()
    return bool(s.smtp_host and s.smtp_from and parse_allowlist(s.email_allowlist))


def _one_line(text: str, limit: int = 120) -> str:
    text = "".join(" " if unicodedata.category(c)[0] == "C" else c for c in text)
    return re.sub(r"\s+", " ", text).strip()[:limit]


def report_to_text(report: Report, sources: list[str]) -> str:
    parts = [report.title, "=" * min(len(report.title), 72), "", report.summary]
    for sec in report.sections:
        parts += ["", sec.heading, "-" * min(len(sec.heading), 72), sec.body]
    if sources:
        parts += ["", "Sources: " + ", ".join(sources)]
    parts += ["", "Generated by Fireline RAG. Verify against the source documents before acting on it."]
    return "\n".join(parts)


def send_report(to: str, report: Report, sources: list[str]) -> None:
    s = get_settings()
    if not email_configured():
        raise EmailError("Email is not configured on this server.")
    to = to.strip()
    if not is_allowed(to, parse_allowlist(s.email_allowlist)):
        raise EmailError("That address is not on the allowed recipients list.")

    msg = EmailMessage()
    msg["From"], msg["To"] = s.smtp_from, to
    msg["Subject"] = _one_line(f"Fireline report: {report.title}")
    msg.set_content(report_to_text(report, sources))
    try:
        if s.smtp_port == 465:
            server = smtplib.SMTP_SSL(s.smtp_host, s.smtp_port, timeout=TIMEOUT_S, context=ssl.create_default_context())
        else:
            server = smtplib.SMTP(s.smtp_host, s.smtp_port, timeout=TIMEOUT_S)
        with server:
            if s.smtp_port != 465:
                server.starttls(context=ssl.create_default_context())
            if s.smtp_user:
                server.login(s.smtp_user, s.smtp_password or "")
            server.send_message(msg)
    except (smtplib.SMTPException, OSError) as exc:
        log.warning("email_failed %s", type(exc).__name__)  # class only: never log server replies or credentials
        raise EmailError("The email could not be sent. Check the SMTP settings.") from exc
